"""Add corrections table

Revision ID: 9d5436e150d7
Revises: a7458c86b406
Create Date: 2022-03-22 14:36:51.247364

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d5436e150d7"
down_revision = "a7458c86b406"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("bike", sa.String(), nullable=True),
        sa.Column("frame", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["postings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("corrections")
    # ### end Alembic commands ###
