"""Rename img_url field

Revision ID: a7458c86b406
Revises: cdb2c66a128b
Create Date: 2022-03-21 20:35:40.084367

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7458c86b406"
down_revision = "cdb2c66a128b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("postings", "img_url", new_column_name="image_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "postings",
        sa.Column("img_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("postings", "image_url")
    # ### end Alembic commands ###
