"""Set on delete cascade for corrections

Revision ID: b691ebcc3675
Revises: 1b431e5dbe7c
Create Date: 2022-04-07 19:56:16.732646

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b691ebcc3675"
down_revision = "1b431e5dbe7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("corrections_posting_id_fkey", "corrections", type_="foreignkey")
    op.create_foreign_key(
        None, "corrections", "postings", ["posting_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "corrections", type_="foreignkey")
    op.create_foreign_key(
        "corrections_posting_id_fkey", "corrections", "postings", ["posting_id"], ["id"]
    )
    # ### end Alembic commands ###
