"""Add query and date fields

Revision ID: cdb2c66a128b
Revises: af7bd847240f
Create Date: 2022-03-21 20:17:26.732907

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cdb2c66a128b"
down_revision = "af7bd847240f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("postings", sa.Column("query", sa.String(), nullable=True))
    op.add_column("postings", sa.Column("loc_query", sa.String(), nullable=True))
    op.add_column("postings", sa.Column("date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("postings", "date")
    op.drop_column("postings", "loc_query")
    op.drop_column("postings", "query")
    # ### end Alembic commands ###
