"""Init database.

Revision ID: af7bd847240f
Revises: 
Create Date: 2022-03-10 20:03:39.522346

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af7bd847240f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "postings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("img_url", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("bike", sa.String(), nullable=True),
        sa.Column("frame", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("postings")
    # ### end Alembic commands ###
